### ISSUE TITLE
Issues decoding ABI with "base" fields

### ISSUE THREAD

**Issue by ismyhc** [greymass/swift-eosio#6]
Heres what my structs look like

```swift
struct SwapPoolsABI: ABICodable {
    let lt_symbol: Asset.Symbol
    let creator: Name
    let memo: String
    let pool1: ExtendedAsset
    let pool2: ExtendedAsset
    let hash: Checksum256
    let fee: SwapPoolFeeABI
    let active: Bool
    let reserved: UInt16
}

struct SwapPoolFeeABI: ABICodable {
    let exchange_fee: UInt16
    let add_liquidity_fee: UInt16
    let remove_liquidity_fee: UInt16
}
```

For some reason when I do a get table rows, the last 2 properties active/reserved are always "false" and 0.

```
cleos -u https://proton.eoscafeblock.com get table proton.swaps proton.swaps pools
```

You can see that active should actually be true for all.

Abi can be found here.
https://proton.bloks.io/account/proton.swaps?loadContract=true&tab=Tables&account=proton.swaps&scope=proton.swaps&limit=100&table=pools

You can see here the abi.
![Screen Shot 2021-02-12 at 5 01 53 PM](https://user-images.githubusercontent.com/840551/107827985-de0d6680-6d55-11eb-8ca7-0806a1fdcda7.png)

If there is anything else I can provide, please let me know. Im not sure where to go from here....

Thanks!
Jacob

**Comment by jnordberg** [comment]
Base fields come before the fields extending them. Try moving active and reserved to the top of your struct

**Comment by ismyhc** [comment]
Yeah, tried shifting the properties, up top. 

**Unable to decode response (caused by boolOutOfRange(8)**

Okay, will take a look at the hex.

**Comment by jnordberg** [comment]
The integers in SwapPoolFeeABI should be 64 bit not 16 causing the struct to be misaligned

**Comment by ismyhc** [comment]
Damn!! I see. :)

![Screen Shot 2021-02-12 at 7 04 36 PM](https://user-images.githubusercontent.com/840551/107834772-37c95d00-6d65-11eb-89d3-36a979fb0c87.png)

Thanks @jnordberg I guess I had been looking at it to long....
